version: '3'

services:
  db:
    image: mongo:latest

  explorer:
    build: ./explorer
    volumes:
      - ./explorer:/home/user/explorer
    depends_on:
      - db

  explorer-test:
    build: ./explorer
    volumes:
      - ./explorer:/home/user/explorer
    depends_on:
      - db
    command: [ "/bin/sh", "entrypoint.sh", "test" ]