version: '3'

services:
  gateway:
    image: nginx
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    expose:
      - "80"
    ports:
     - "80:80"
    depends_on:
     - explorer
     - swagger-ui

  swagger-ui:
    image: swaggerapi/swagger-ui
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: "/foo/swagger.json"
      BASE_URL: "/swagger/"
    volumes:
      - /home/alexander/CloudStation/softwarearchitect-2019-11/2019-11-explorer/:/foo/

  db:
    image: mongo:latest
    expose:
      - "27017"
    ports:
      - "57017:27017"

  explorer:
    build: ./explorer
    expose:
      - "18000"
    ports:
      - "18000:8080"
    volumes:
      - ./explorer:/home/user/explorer
    depends_on:
      - db

  explorer-test:
    build: ./explorer
    volumes:
      - ./explorer:/home/user/explorer
    depends_on:
      - db
    command: [ "/bin/sh", "entrypoint.sh", "test" ]