version: '3'

services:
  # BUS {
  bus:
    image: rabbitmq
    expose:
      - "5672"
    ports:
      - "5672:5672"
  # BUS }

  # WALLETS {
  db:
    image: mongo:latest
    expose:
      - "27017"
    ports:
      - "57017:27017"
  #
  backend:
    build: ./backend
    expose:
      - "18000"
    ports:
      - "18000:8080"
    environment:
      DEV: $DEV
    volumes:
      - ./common/common:/home/user/backend/common
      - ./backend:/home/user/backend
    command: [ "/bin/sh", "entrypoint.sh" ]
    depends_on:
      - db
      - bus
  #
  backend-test:
    build: ./backend
    volumes:
      - ./backend:/home/user/backend
    depends_on:
      - db
    command: [ "/bin/sh", "entrypoint.sh", "test" ]
  # WALLETS }

  # TESTING {
  tester:
    build: ./tester
    volumes:
      - ./common/common:/home/user/tester/common
      - ./tester:/home/user/tester
    depends_on:
      - bus
      - backend
      - loader

  frontend:
    build: frontend
    environment:
      HOST: 0.0.0.0
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/app/src
      - ./frontend/public:/usr/app/public
      - ./frontend/package.json:/usr/app/package.json
    depends_on:
      - backend
  # TESTING }

  # CONTRACT {
  gateway:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      - backend
      - swagger-ui
      - loader
      - frontend
  #
  swagger-ui:
    image: swaggerapi/swagger-ui
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: "/foo/swagger.json"
      BASE_URL: "/swagger/"
    volumes:
      - ./:/foo/
  # CONTRACT }

  # CHAIN {
  bitcoin-server:
    image: ruimarinho/bitcoin-core
    expose:
      - "18444"
      - "18443"
    ports:
      - "18444:18444"
      - "18443:18443"
    command: bitcoind -server -printtoconsole -regtest=1 -rpcuser=u -rpcpassword=p -rpcallowip=0.0.0.0/0 -rpcbind=0.0.0.0
  #
  loader:
    build: ./loader
    volumes:
      - ./common/common:/home/user/loader/common
      - ./loader:/home/user/loader
    environment:
      DEV: $DEV
    command: [ "/bin/sh", "entrypoint.sh" ]
    depends_on:
      - bus
      - bitcoin-server
  # CHAIN }

